# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/testing-ios/
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/configuration-reference/#jobs
version: 2.1
jobs:
  build:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
            bundle exec pod install
      - run:
          name: Build and run tests
          command: xcodebuild clean test -scheme GamesCleanArchitectureMVVM -destination "platform=iOS Simulator,name=iPhone 14 Pro" -allowProvisioningUpdates

