# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/testing-ios/
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/configuration-reference/#jobs
version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.0"
    steps:
      - checkout
      - run:
          name: "hello word"
          command: "echo Hola mundo"
